project:
  type: website
  output-dir: docs

website:
  title: "Welcome"
  repo-url: https://github.com/jbwilliams/jbwilliams.github.io
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Basics"
        contents:
          - DRY.qmd
      - section: "Patterns"
        contents:
          - Decorator.ipynb

  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

